top_srcdir   = /home/hacker/test2/httpd-2.4.39
top_builddir = /home/hacker/test2/httpd-2.4.39
srcdir       = /home/hacker/test2/httpd-2.4.39/modules/generators
builddir     = /home/hacker/test2/httpd-2.4.39/modules/generators
VPATH        = /home/hacker/test2/httpd-2.4.39/modules/generators

include $(top_srcdir)/build/special.mk

