top_srcdir   = /home/hacker/httpd-2.4.39
top_builddir = /home/hacker/httpd-2.4.39
srcdir       = /home/hacker/httpd-2.4.39/modules/core
builddir     = /home/hacker/httpd-2.4.39/modules/core
VPATH        = /home/hacker/httpd-2.4.39/modules/core

include $(top_srcdir)/build/special.mk

