top_srcdir   = /home/hacker/httpd-2.4.39
top_builddir = /home/hacker/httpd-2.4.39
srcdir       = /home/hacker/httpd-2.4.39/server/mpm
builddir     = /home/hacker/httpd-2.4.39/server/mpm
VPATH        = /home/hacker/httpd-2.4.39/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
