top_srcdir   = /home/hacker/httpd-2.4.39
top_builddir = /home/hacker/httpd-2.4.39
srcdir       = /home/hacker/httpd-2.4.39/modules/cache
builddir     = /home/hacker/httpd-2.4.39/modules/cache
VPATH        = /home/hacker/httpd-2.4.39/modules/cache

include $(top_srcdir)/build/special.mk

