top_srcdir   = /home/hacker/httpd-2.4.39
top_builddir = /home/hacker/httpd-2.4.39
srcdir       = /home/hacker/httpd-2.4.39/modules/metadata
builddir     = /home/hacker/httpd-2.4.39/modules/metadata
VPATH        = /home/hacker/httpd-2.4.39/modules/metadata

include $(top_srcdir)/build/special.mk

