top_srcdir   = /home/hacker/test2/httpd-2.4.39
top_builddir = /home/hacker/test2/httpd-2.4.39
srcdir       = /home/hacker/test2/httpd-2.4.39/modules
builddir     = /home/hacker/test2/httpd-2.4.39/modules
VPATH        = /home/hacker/test2/httpd-2.4.39/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

