top_srcdir   = /home/hacker/httpd-2.4.39
top_builddir = /home/hacker/httpd-2.4.39
srcdir       = /home/hacker/httpd-2.4.39/modules/loggers
builddir     = /home/hacker/httpd-2.4.39/modules/loggers
VPATH        = /home/hacker/httpd-2.4.39/modules/loggers

include $(top_srcdir)/build/special.mk

