top_srcdir   = /home/hacker/test2/httpd-2.4.39
top_builddir = /home/hacker/test2/httpd-2.4.39
srcdir       = /home/hacker/test2/httpd-2.4.39/os
builddir     = /home/hacker/test2/httpd-2.4.39/os
VPATH        = /home/hacker/test2/httpd-2.4.39/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
