top_srcdir   = /home/hacker/test2/httpd-2.4.39
top_builddir = /home/hacker/test2/httpd-2.4.39
srcdir       = /home/hacker/test2/httpd-2.4.39/modules/http
builddir     = /home/hacker/test2/httpd-2.4.39/modules/http
VPATH        = /home/hacker/test2/httpd-2.4.39/modules/http

include $(top_srcdir)/build/special.mk

