top_srcdir   = /home/hacker/httpd-2.4.39
top_builddir = /home/hacker/httpd-2.4.39
srcdir       = /home/hacker/httpd-2.4.39/modules/test
builddir     = /home/hacker/httpd-2.4.39/modules/test
VPATH        = /home/hacker/httpd-2.4.39/modules/test
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
