top_srcdir   = /home/hacker/httpd-2.4.39
top_builddir = /home/hacker/httpd-2.4.39
srcdir       = /home/hacker/httpd-2.4.39/modules/aaa
builddir     = /home/hacker/httpd-2.4.39/modules/aaa
VPATH        = /home/hacker/httpd-2.4.39/modules/aaa

include $(top_srcdir)/build/special.mk

