top_srcdir   = /home/hacker/httpd-2.4.39
top_builddir = /home/hacker/httpd-2.4.39
srcdir       = /home/hacker/httpd-2.4.39/srclib
builddir     = /home/hacker/httpd-2.4.39/srclib
VPATH        = /home/hacker/httpd-2.4.39/srclib

BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
