top_srcdir   = /home/hacker/test2/httpd-2.4.39
top_builddir = /home/hacker/test2/httpd-2.4.39
srcdir       = /home/hacker/test2/httpd-2.4.39/server/mpm/event
builddir     = /home/hacker/test2/httpd-2.4.39/server/mpm/event
VPATH        = /home/hacker/test2/httpd-2.4.39/server/mpm/event
include $(top_srcdir)/build/special.mk
