top_srcdir   = /home/hacker/test2/httpd-2.4.39
top_builddir = /home/hacker/test2/httpd-2.4.39
srcdir       = /home/hacker/test2/httpd-2.4.39/modules/echo
builddir     = /home/hacker/test2/httpd-2.4.39/modules/echo
VPATH        = /home/hacker/test2/httpd-2.4.39/modules/echo

include $(top_srcdir)/build/special.mk

