top_srcdir   = /home/hacker/httpd-2.4.39
top_builddir = /home/hacker/httpd-2.4.39
srcdir       = /home/hacker/httpd-2.4.39/modules/filters
builddir     = /home/hacker/httpd-2.4.39/modules/filters
VPATH        = /home/hacker/httpd-2.4.39/modules/filters

include $(top_srcdir)/build/special.mk

