top_srcdir   = /home/hacker/httpd-2.4.39
top_builddir = /home/hacker/httpd-2.4.39
srcdir       = /home/hacker/httpd-2.4.39/modules/arch/unix
builddir     = /home/hacker/httpd-2.4.39/modules/arch/unix
VPATH        = /home/hacker/httpd-2.4.39/modules/arch/unix

include $(top_srcdir)/build/special.mk

