top_srcdir   = /home/hacker/httpd-2.4.39
top_builddir = /home/hacker/httpd-2.4.39
srcdir       = /home/hacker/httpd-2.4.39/modules/mappers
builddir     = /home/hacker/httpd-2.4.39/modules/mappers
VPATH        = /home/hacker/httpd-2.4.39/modules/mappers

include $(top_srcdir)/build/special.mk

